services:
  server:
    environment:
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATABASE_URL=sqlite:////db/app.db
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - ${HOST_PORT}:5000
    volumes:
      - db:/db
  updater:
    environment:
      - DATABASE_URL=sqlite:////db/app.db
    build:
      context: ./
      dockerfile: updater/Dockerfile
    volumes:
      - db:/db
    depends_on:
      - server

volumes:
  db:
